function(AddExeFromFiles Prefix)
    foreach(FILEPATH ${ARGN})
        get_filename_component(FILE_NAME ${FILEPATH} NAME_WE)
        add_executable(${Prefix}_${FILE_NAME} ${FILEPATH})
    endforeach()
endfunction()

function(AddExeFromFilesWithLib Libs Prefix)
    foreach(FILEPATH ${ARGN})
        get_filename_component(FILE_NAME ${FILEPATH} NAME_WE)
        add_executable(${Prefix}_${FILE_NAME} ${FILEPATH})
        target_link_libraries(${Prefix}_${FILE_NAME} PRIVATE ${Libs})
    endforeach()
endfunction()