[package]
name = "prost"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
prost = "0.10"
bytes = "1.1"


[build-dependencies]
prost-build = "0.10"
